
services:
  admin-backend:
    build:
      context: ./admin-backend
    ports:
      - "8083:8083"
    env_file:
      - ./admin-backend/.env.prod
    networks:
      - healthnavi-network

  admin-frontend:
    image: richkitibwa/healthnavi-admin-frontend
    ports:
      - "8080:80"
    env_file:
      - ./admin-frontend/.env.production
    depends_on:
      - admin-backend
    networks:
      - healthnavi-network

networks:
  healthnavi-network:
    driver: bridge
